---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-k2
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
